AdminPanal/Controllers/ProdectsMcvController.cs
using AdminPanal.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;



namespace AdminPanal.Controllers
{
    public class ProdectsMcvController : Controller
    {
        private ShopDBEntities db = new ShopDBEntities();



        // GET: ProdectsMcv
        //[Authorize]
        public ActionResult Index(string searchBy , string search)
        {

            var prodectTs = db.ProdectTs.Include(p => p.CategorieID);
            
            if (searchBy == "1")
            {
                return View(db.ProdectTs.Where(x => x.ProdectName.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "2")
            {
                return View(db.ProdectTs.Where(x => x.ProdectNameAR.StartsWith(search) || search == null).ToList());
            }
            else 
            {
                return View(db.ProdectTs.Where(x => x.Price.ToString().StartsWith(search) || search == null).ToList());
            }                        

        }
        public ActionResult Indexx()
        {           
            return RedirectToAction("AddNewImage", "ProdetesImages");                                  
        }

        // GET: ProdectsMcv/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProdectT prodectT = db.ProdectTs.Find(id);
            if (prodectT == null)
            {
                return HttpNotFound();
            }
            return View(prodectT);
        }

        // GET: ProdectsMcv/Create
        public ActionResult Create()
        {
            ViewBag.CategorieID = new SelectList(db.CategoriesTs, "CategorieID", "CategorieName");
            return View();
        }

        // POST: ProdectsMcv/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdectID,ProdectName,ProdectNameAR,Descriotion,DescriotionAR,Price,Rating,ImagePath,CategorieID")] ProdectT prodectT)
        {


            //string FileName = Path.GetFileNameWithoutExtension(prodectT.)
            if (ModelState.IsValid)
            {                
                db.ProdectTs.Add(prodectT);                
                db.SaveChanges();
                
                
                return RedirectToAction("Indexx");
            }

            ViewBag.CategorieID = new SelectList(db.CategoriesTs, "CategorieID", "CategorieName", prodectT.CategorieID);
            return View(prodectT);
        }


        //[HttpPost,ActionName("Upload")]
        //public ActionResult UploadFiles(HttpPostedFileBase file ,ProdectT prodect )
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {

        //            if (file != null)
        //            {
        //                string fileName = Path.GetFileNameWithoutExtension(file.FileName);
        //                string extension = Path.GetExtension(file.FileName);
        //                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
        //                prodect.ImagePath = "~/UploadedFiles/" + fileName;
        //                fileName = "C:\"Users\"Ans\"source\"repos\"MarketApp2\"AdminPanal" + "~/UploadedFiles/" + fileName;
        //                file.SaveAs(fileName)
        //                //string path = "C:\"Users\"Ans\"source\"repos\"MarketApp2\"AdminPanal\"UploadedFiles" + Path.GetFileName(file.FileName);
        //                //string path = Path.Combine(Server.MapPath("~/UploadedFiles"), Path.GetFileName(file.FileName));
        //                 /*file.SaveAs(path)*/;
        //                db.ProdectTs.Add(prodect);
        //                db.SaveChanges();


        //            }
                 
                    
        //            ViewBag.FileStatus = "File uploaded successfully.";
        //        }
        //        catch (Exception)
        //        {

        //            ViewBag.FileStatus = "Error while file uploading.";
        //        }

        //    }
        //    ModelState.Clear();
        //    return View();
            
        //}

        // GET: ProdectsMcv/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProdectT prodectT = db.ProdectTs.Find(id);
            if (prodectT == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategorieID = new SelectList(db.CategoriesTs, "CategorieID", "CategorieName", prodectT.CategorieID);
            return View(prodectT);
        }

        // POST: ProdectsMcv/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdectID,ProdectName,ProdectNameAR,Descriotion,DescriotionAR,Price,Rating,ImagePath,CategorieID")] ProdectT prodectT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prodectT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategorieID = new SelectList(db.CategoriesTs, "CategorieID", "CategorieName", prodectT.CategorieID);
            return View(prodectT);
        }

        // GET: ProdectsMcv/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProdectT prodectT = db.ProdectTs.Find(id);
            if (prodectT == null)
            {
                return HttpNotFound();
            }
            return View(prodectT);
        }

        // POST: ProdectsMcv/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProdectT prodectT = db.ProdectTs.Find(id);
            db.ProdectTs.Remove(prodectT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

         

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminPanal/Views/ProdectsMcv/Create.cshtml
@model AdminPanal.Models.ProdectT

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Prodect</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.ProdectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ProdectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProdectName, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.ProductsAvailableNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ProductsAvailableNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductsAvailableNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProdectNameAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ProdectNameAR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProdectNameAR, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">

    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Descriotion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Descriotion, new { htmlAttributes = new { @class = "form-control" }, cols = 35, @rows = 3, })
            @*@Html.EditorFor(model => model.Descriotion, new { htmlAttributes = new { @class = "form-control", rows = "20" } })*@
            @Html.ValidationMessageFor(model => model.Descriotion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DescriotionAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="height: 120px;">
            @Html.TextAreaFor(model => model.DescriotionAR, new { htmlAttributes = new { @class = "form-control" }, cols = 35, @rows = 3, })
            @*@Html.EditorFor(model => model.DescriotionAR, new { htmlAttributes = new { @class = "form-control", rows = "20", @style = "height: 120px;" } })*@
            @Html.ValidationMessageFor(model => model.DescriotionAR, "", new { @class = "text-break" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CategorieID, "CategorieID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategorieID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategorieID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-success">
            @ViewBag.FileStatus
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="continue" class="btn btn-primary" />
        </div>
    </div>


</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminPanal/Views/ProdectsMcv/Delete.cshtml
@model AdminPanal.Models.ProdectT

    @{
        ViewBag.Title = "Delete";
    }

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ProdectT</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProdectName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProdectName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProdectNameAR)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProdectNameAR)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProductsAvailableNum)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductsAvailableNum)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Rating)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Rating)
            </dd>

            <dt>

            <dt>
                @Html.DisplayNameFor(model => model.CategorieID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CategorieID)
            </dd>
            <dt style="height: 120px;">
                @Html.DisplayNameFor(model => model.Descriotion)
            </dt>

            <dd style="height: 120px;">
                @Html.DisplayFor(model => model.Descriotion)
            </dd>

            <dt style="height: 120px;">
                @Html.DisplayNameFor(model => model.DescriotionAR)
            </dt>

            <dd style="height: 120px;">
                @Html.DisplayFor(model => model.DescriotionAR)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

AdminPanal/Views/ProdectsMcv/Details.cshtml
@model AdminPanal.Models.ProdectT

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProdectT</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdectNameAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectNameAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductsAvailableNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductsAvailableNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.CategorieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieID)
        </dd>

        <dt style="height: 120px;">
            @Html.DisplayNameFor(model => model.Descriotion)
        </dt>

        <dd style="height: 120px;">
            @Html.DisplayFor(model => model.Descriotion)
        </dd>

        <dt style="height: 120px;">
            @Html.DisplayNameFor(model => model.DescriotionAR)
        </dt>

        <dd style="height: 120px;">
            @Html.DisplayFor(model => model.DescriotionAR)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProdectID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdminPanal/Views/ProdectsMcv/Edit.cshtml
@model AdminPanal.Models.ProdectT

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ProdectT</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProdectID)

    <div class="form-group">
        @Html.LabelFor(model => model.ProdectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ProdectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProdectName, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.ProductsAvailableNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ProductsAvailableNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductsAvailableNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProdectNameAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.ProdectNameAR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProdectNameAR, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>





    @*<div class="form-group">
        @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </div>
    </div>*@

  
    <div class="form-group">
        @Html.LabelFor(model => model.CategorieID, "CategorieID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategorieID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategorieID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Descriotion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="height: 120px;">
            @Html.TextAreaFor(model => model.Descriotion, new { htmlAttributes = new { @class = "form-control" }, cols = 35, @rows = 3, })
            @*@Html.EditorFor(model => model.Descriotion, new { htmlAttributes = new { @class = "form-control", @style = "height: 120px;" } })*@
            @Html.ValidationMessageFor(model => model.Descriotion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DescriotionAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="height: 120px;">
            @Html.TextAreaFor(model => model.DescriotionAR, new { htmlAttributes = new { @class = "form-control" }, cols = 35, @rows = 3, })
            @*@Html.EditorFor(model => model.DescriotionAR, new { htmlAttributes = new { @class = "form-control", @style = "height: 120px;" } })*@
            @Html.ValidationMessageFor(model => model.DescriotionAR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminPanal/Views/ProdectsMcv/Index.cshtml
@model IEnumerable<AdminPanal.Models.ProdectT>

@{
    /**/

    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "ProdectsMcv", FormMethod.Get))
{

    <div class="form-group">
        <div class="col-md-10" style="padding-right: 0px;padding-left: 0px;margin-bottom:15px">
            <input class="form-control text-box single-line" style="width:100%;max-width: 100%;height: 33px;padding: 10px;border-bottom-left-radius: 15px;border-top-left-radius: 15px;" id="search" name="search" type="text" value="">
        </div>
        <input type="submit" value="search" class="btn btn-danger col-md-2" style="margin-left:-5px;margin-bottom:15px" />
    </div>

    <p style="float:left;margin-right:15px;">
        @Html.ActionLink("Create New", "Create")
    </p>
    <b style="margin-right:15px; float:left; margin-bottom:25px; " class="">Search By</b>
    @Html.DropDownList("SearchBy", new List<SelectListItem>
{
new SelectListItem {Text="Prodect Name",Value="1",Selected=true},
new SelectListItem {Text="Prodect Name Arbic",Value="2"},
new SelectListItem {Text="Price",Value="3"},
}, "Search By")
    


}


<table class="table" style="clear:both">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProdectName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>

        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="3">No Prodect Match The Search</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProdectName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ProdectID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ProdectID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProdectID })
                </td>
            </tr>
        }
    }


</table>

@*<th>
        @Html.DisplayNameFor(model => model.ImagePath)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CategoriesT.CategorieName)
    </th>*@

@*<th>
        @Html.DisplayNameFor(model => model.ProdectNameAR)
    </th>*@
@*<th>
        @Html.DisplayNameFor(model => model.Descriotion)
    </th>*@
@*<th>
        @Html.DisplayNameFor(model => model.DescriotionAR)
    </th>*@


@*<td>
        @Html.DisplayFor(modelItem => item.ImagePath)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CategoriesT.CategorieName)
    </td>*@