AdminPanal/Models/oldOrder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldOrder
    {
        public int OrderNumber { get; set; }
        public Nullable<int> ProdectID { get; set; }
        public string ProdectName { get; set; }
        public string ProdectNameAR { get; set; }
        public string Descriotion { get; set; }
        public string DescriotionAR { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string ImagePath { get; set; }
        public string CategorieID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string CancelMassage { get; set; }
    }
}

AdminPanal/Controllers/oldOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminPanal.Models;


namespace AdminPanal.Controllers
{
    public class oldOrdersController : Controller
    {
        private ShopDBEntities db = new ShopDBEntities();

        // GET: oldOrders
        //[Authorize]
        public ActionResult Index(string searchBy, string search)
        {
            
            var oldOrders = db.oldOrders;

            if (searchBy == "1")
            {
                return View(db.oldOrders.Where(x => x.ProdectName.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "2")
            {
                return View(db.oldOrders.Where(x => x.Price.ToString().StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "3")
            {
                return View(db.oldOrders.Where(x => x.UserName.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "4")
            {
                return View(db.oldOrders.Where(x => x.Email.StartsWith(search) || search == null).ToList());
            }            
            else
            {
                return View(db.oldOrders.Where(x => x.Phone.ToString().StartsWith(search) || search == null).ToList());
            }

        }
        
        // GET: oldOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            oldOrder oldOrder = db.oldOrders.Find(id);
            if (oldOrder == null)
            {
                return HttpNotFound();
            }
            return View(oldOrder);
        }

        // GET: oldOrders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: oldOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderNumber,ProdectID,ProdectName,ProdectNameAR,Descriotion,DescriotionAR,Price,Rating,ImagePath,CategorieID,UserID,FullName,UserName,Email,Phone,Password,City,State,Country,Address")] oldOrder oldOrder)
        {
            if (ModelState.IsValid)
            {
                db.oldOrders.Add(oldOrder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oldOrder);
        }

        // GET: oldOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            oldOrder oldOrder = db.oldOrders.Find(id);
            if (oldOrder == null)
            {
                return HttpNotFound();
            }
            return View(oldOrder);
        }

        // POST: oldOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderNumber,ProdectID,ProdectName,ProdectNameAR,Descriotion,DescriotionAR,Price,Rating,ImagePath,CategorieID,UserID,FullName,UserName,Email,Phone,Password,City,State,Country,Address")] oldOrder oldOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oldOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oldOrder);
        }

        // GET: oldOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            oldOrder oldOrder = db.oldOrders.Find(id);
            if (oldOrder == null)
            {
                return HttpNotFound();
            }
            return View(oldOrder);
        }

        // POST: oldOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            oldOrder oldOrder = db.oldOrders.Find(id);
            db.oldOrders.Remove(oldOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminPanal/Views/oldOrders/Create.cshtml
@model AdminPanal.Models.oldOrder

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>oldOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProdectID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdectID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdectNameAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdectNameAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdectNameAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descriotion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descriotion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descriotion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriotionAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriotionAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriotionAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategorieID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategorieID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategorieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminPanal/Views/oldOrders/Delete.cshtml
@model AdminPanal.Models.oldOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>oldOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdectNameAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectNameAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descriotion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descriotion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriotionAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriotionAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategorieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdminPanal/Views/oldOrders/Details.cshtml
@model AdminPanal.Models.oldOrder

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>oldOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdectNameAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdectNameAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descriotion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descriotion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriotionAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriotionAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategorieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CancelMassage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CancelMassage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderNumber }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdminPanal/Views/oldOrders/Index.cshtml
@model IEnumerable<AdminPanal.Models.oldOrder>


@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "oldOrders", FormMethod.Get))
{

    <div class="form-group">
        <div class="col-md-10" style="padding-right: 0px;padding-left: 0px;margin-bottom:15px">
            <input class="form-control text-box single-line" style="width:100%;max-width: 100%;height: 33px;padding: 10px;border-bottom-left-radius: 15px;border-top-left-radius: 15px;" id="search" name="search" type="text" value="">
        </div>
        <input type="submit" value="search" class="btn btn-danger col-md-2" style="margin-left:-5px;margin-bottom:15px" />
    </div>
    <b style="margin-right:15px; float:left; margin-bottom:25px; " class="">Search By</b>
    @Html.DropDownList("SearchBy", new List<SelectListItem>
{
new SelectListItem {Text="Prodect Name",Value="1",Selected=true},
new SelectListItem {Text="Prodect Price",Value="2"},
new SelectListItem {Text="User  Name",Value="3"},
new SelectListItem {Text="User Email",Value="4"},
new SelectListItem {Text="User Phone",Value="5"},
}, "Search By")





}

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.ProdectName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>

        <th>
            Order Cancel
        </th>

        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="3">No Order Match The Search</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.ProdectName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>

                <td name="cancelTd">
                    @if (item.CancelMassage == null)
                    {
                        <p></p>
                    }
                    else
                    {<span>Canceled</span>}
                </td>

                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.OrderNumber }) |*@
                    @Html.ActionLink("Details", "Details", new { id = item.OrderNumber }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.OrderNumber })
                </td>
            </tr>
        }
    }
</table>