AdminPanal/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using AdminPanal.Models;
using MySql.Data.MySqlClient.Memcached;

namespace AdminPanal.Controllers
{
    public class ImageController : Controller
    {
        private ShopDBEntities db = new ShopDBEntities();

        // GET: Image
        public ActionResult Index()
        {
            var imageTs = db.ImageTs.Include(i => i.ProdectT);
            return View(imageTs.ToList());
        }


        public ActionResult Indexx(string Image)
        {
            //add the header
            System.Net.WebClient Client = new System.Net.WebClient();            
            Client.Headers.Add("Content-Type", "binary/octet-streOpenWriteam");

            //uploads the file and gets the result in a byte[]
            byte[] resultbyte =Client.UploadFile("weburl/controller/actionmethod", "POST", "pathToFile");

            //converts the result[] to a string
            //دا الاسترينج الى عاوز اضيفه فى الداتا بيز عشان هو دا الى هيتحول تانى ويكون byte
            string resultString = System.Text.Encoding.UTF8.GetString(resultbyte, 0, resultbyte.Length);
            

            //WebImage photo = null;
            //var newFileName = "";
            //photo = WebImage.GetImageFromRequest();

            //get the image from the request
            HttpPostedFileBase image = Request.Files[0];
            var imagePath = "";
            if (image != null)
            {
               // save the image in the selected folder on the server
               imagePath = @"UploadedFiles\" + image.FileName;                        
               image.SaveAs(Server.MapPath(@"~\" + imagePath));


                //newFileName = DateTime.Now.ToString("yymmssfff") + "_" + Path.GetFileName(photo.FileName);
               // imagePath = @"UploadedFiles\" + photo.FileName;
               // photo.Save(@"~\" + imagePath);

            }
                
            
            return View();
        }




        // GET: Image/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageT imageT = db.ImageTs.Find(id);
            if (imageT == null)
            {
                return HttpNotFound();
            }
            return View(imageT);
        }

        // GET: Image/Create
        public ActionResult Create()
        {
            ViewBag.ProdectID = new SelectList(db.ProdectTs, "ProdectID", "ProdectName");
            var lastRecord = (from c in db.ProdectTs
                              orderby c.ProdectID descending
                              select c).First();

            ViewBag.user = lastRecord.ProdectID.ToString();
            return View();
        }

        // POST: Image/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImageID,ImagePath,ImageTitle,ProdectID")] ImageT imageT)
        {
            if (ModelState.IsValid)
            {
                db.ImageTs.Add(imageT);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProdectID = new SelectList(db.ProdectTs, "ProdectID", "ProdectName", imageT.ProdectID);
            return View(imageT);
        }

        // GET: Image/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageT imageT = db.ImageTs.Find(id);
            if (imageT == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProdectID = new SelectList(db.ProdectTs, "ProdectID", "ProdectName", imageT.ProdectID);
            return View(imageT);
        }

        // POST: Image/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ImageID,ImagePath,ImageTitle,ProdectID")] ImageT imageT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(imageT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProdectID = new SelectList(db.ProdectTs, "ProdectID", "ProdectName", imageT.ProdectID);
            return View(imageT);
        }

        // GET: Image/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageT imageT = db.ImageTs.Find(id);
            if (imageT == null)
            {
                return HttpNotFound();
            }
            return View(imageT);
        }

        // POST: Image/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ImageT imageT = db.ImageTs.Find(id);
            db.ImageTs.Remove(imageT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminPanal/Controllers/RoleController.cs
using AdminPanal.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminPanal.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Role
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();            
            return RedirectToAction("Index");
        }
    }
}

AdminPanal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top"  style="background-color: #1A7A83;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GDG Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand",@style= "color:#bef3ee" })
            </div>
            <div  class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Home", "Index", "OrdersMcv")</li>
                    <li>@Html.ActionLink("Categories", "Index", "CategoriesMcv")</li>
                    <li>@Html.ActionLink("Prodects", "Index", "ProdectsMcv")</li>
                    <li>@Html.ActionLink("User", "Index", "Usermcv")</li>
                    <li>@Html.ActionLink("oldOrders", "Index", "oldOrders")</li>
                    <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div  class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
            
            <p>&copy; Programmed by - <span style="font-weight:bolder;">Ansbedoor@gmail.com</span></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>